# 1. numbers = (10, 20, 30, 40, 50)Add 60 to the end,Replace 30 with 35.
number=(10, 20, 30, 40, 50)
x=list(number)
print(x)
x.append(60) 
print(x)    
x[2]=35
print(x)   
x=tuple(x)
print(x)
# 2. values = (15, 5, 30, 25, 10) arrange the elements in ascending order.
values=(15, 5, 30, 25, 10)
x=list(values)  
print(x)
x.sort()
print(x)
x=tuple(x)
# 3. fruits = ("apple", "banana", "cherry", "banana", "mango", "banana")
# Count occurrences of "banana",Remove all occurrences of "banana"
fruits=("apple", "banana", "cherry", "banana", "mango", "banana")
fruits=list(fruits)
print(fruits)
print(fruits.count("banana"))
fruits.pop()
print(fruits)
fruits.remove("banana")
print(fruits)
fruits.remove("banana")
print(fruits)
# 4. names = ("Alice", "Bob", "Charlie", "David") Reverse the order of elements using sort method.
names=("Alice", "Bob", "Charlie", "David")
names=list(names)
print(names)
names.sort(reverse =True)
print(names)
names=tuple(names)
print(names)
# 5. colors = ("red", "blue", "green")add "yellow" at index 1,Extend with ["purple", "orange"]
colors = ("red", "blue", "green")
x=list(colors)
print(x)
x.insert(1, "yellow")       
print(x)
x.extend(["purple", "orange"])  
print(x)
x=tuple(x)
print(x)
# Attempt questions in the link below. Whether you get the right answer or not, still read the solution explanation.
# https://realpython.com/quizzes/python-lists-tuples/viewer/
